name: Release

on:
  push:
    branches:
      - feature/github-actions

jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install Bun
        uses: oven-sh/setup-bun@v2

      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          default: true # set the toolchain as default
          profile: minimal # rustup profile

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf \
            libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-good1.0-dev

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@6434f9aaff0a2daf202596b552c34c463d0e43ed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
